server.port: 8080

spring:

  # Spring data rest
  data:
    rest:
      # Definition of page size for PagingAndSortingRepository
      max-page-size: 0x7fffffff
      default-page-size: 0x7fffffff
      return-body-on-update: true
      return-body-on-create: true

  # Spring JPA
  h2.console.enabled: true
  jpa:
    database:
    hibernate:
      # always drop and create the db should be the best
      # configuration for local (development) mode. this
      # is also the default, that spring offers by convention.
      # but here explicite:
      ddl-auto: none
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    # Logging for database operation
    show-sql: true
    properties:
      hibernate:
        format_sql: false
  datasource:
    url: jdbc:<database>:thin:@//<host>:<port>/<service>
    username:
    password:
  flyway:
    enabled: false

# Define the keycloak productive realm here
realm:

security:
  # possible values: none, all, changing (With changing, only changing requests such as POST, PUT, DELETE are logged)
  logging.requests: changing
  oauth2:
    resource:
      jwk:
        key-set-uri:
      user-info-uri:
      prefer-token-info: false
    client:
      client-id:
      scope:

# CoVe-Spezifische Einstellungen:
cove:
  reservePerson:
    maxRetries: 5