CREATE TABLE "PERSON"
   (	"ID" VARCHAR2(1024 BYTE) NOT NULL,
   "CREATED_DATE" TIMESTAMP NOT NULL,
	"NAME" VARCHAR2(255 BYTE) NOT NULL,
	"VORNAME" VARCHAR2(255 BYTE) NOT NULL,
	"KATEGORIE" VARCHAR2(5 BYTE),
	"STANDORT" VARCHAR2(1024 BYTE),
	"GEBURTSDATUM" DATE,
	"STRASSE" VARCHAR2(255 BYTE),
	"PLZ" VARCHAR(5 BYTE),
	"ORT" VARCHAR2(255 BYTE),
	"LANDKREIS" VARCHAR2(255 BYTE),
	"ORTSTEIL" VARCHAR2(255 BYTE),
	"LAND" VARCHAR2(255 BYTE),
	"TELEFON" VARCHAR2(255 BYTE),
	"MOBILE" VARCHAR2(255 BYTE),
	"MAIL" VARCHAR2(1024 BYTE),
	"QUARANTAENE_START" DATE,
	"QUARANTAENE_ENDE" DATE,
	"ARBEITSINFOS" CLOB,
	"KOMMENTARE" CLOB,
	"HAUSHALT" VARCHAR2(1024 BYTE),
	"TELEFONNOTIZEN" CLOB,
	"DOKU" CLOB
);

CREATE TABLE "PROBE" (
	"CREATED_DATE" TIMESTAMP NOT NULL,

	"PERSONID" VARCHAR2(1024 BYTE),
	"KOMMENTAR" VARCHAR2(1024 BYTE),
	"DATUM" DATE,
	"ERGEBNIS" VARCHAR2(255 BYTE) NOT NULL
);

CREATE TABLE "KONTAKT" (
	"ID" VARCHAR2(1024 BYTE) NOT NULL,
    "CREATED_DATE" TIMESTAMP NOT NULL,

	"PERSONID" VARCHAR2(1024 BYTE),
	"KONTAKTMIT" VARCHAR2(1024 BYTE),
	"KONTAKTTYP" VARCHAR2(5 BYTE),
	"KONTAKTDATUM" DATE,
	"KOMMENTAR" VARCHAR(1024 BYTE),
	 CONSTRAINT "KONTAKTVERHAELTNIS_FK1" FOREIGN KEY ("PERSONID")
	  REFERENCES "PERSON" ("ID"),
	 CONSTRAINT "KONTAKTVERHAELTNIS_FK2" FOREIGN KEY ("KONTAKTMIT")
	  REFERENCES "PERSON" ("ID"),
	 CONSTRAINT KONTAKT_CHK1 CHECK (PERSONID <> KONTAKTMIT)
);
