ALTER TABLE "PERSON" ADD "KPBIS" DATE;
ALTER TABLE "PERSON" ADD "LETZTERKONTAKT" DATE;
ALTER TABLE "PERSON" ADD "ERSTKONTAKT" DATE;
ALTER TABLE "PERSON" ADD "ENDTELEFONAT" DATE;
ALTER TABLE "PERSON" ADD "AKTUELLER_BEARBEITER" VARCHAR2(1024 BYTE);
