ALTER TABLE "PERSON" ALTER COLUMN "KPBIS" TIMESTAMP;
ALTER TABLE "PERSON" ALTER COLUMN "LETZTERKONTAKT" TIMESTAMP;
ALTER TABLE "PERSON" ALTER COLUMN "ERSTKONTAKT" TIMESTAMP;
ALTER TABLE "PERSON" ALTER COLUMN "ENDTELEFONAT" TIMESTAMP;