--------------------------------------------------------
--  DDL for Table PERSON
--------------------------------------------------------

  CREATE TABLE "COVE"."PERSON"
   (	"ID" VARCHAR2(1024 BYTE),
   	"CREATED_DATE" DATE,
	"NAME" VARCHAR2(255 BYTE),
	"VORNAME" VARCHAR2(255 BYTE),
	"KATEGORIE" VARCHAR2(5 BYTE),
	"STANDORT" VARCHAR2(1024 BYTE),
	"GEBURTSDATUM" DATE,
	"STRASSE" VARCHAR2(255 BYTE),
	"PLZ" VARCHAR2(5 BYTE),
	"ORT" VARCHAR2(255 BYTE),
	"LANDKREIS" VARCHAR2(255 BYTE),
	"ORTSTEIL" VARCHAR2(255 BYTE),
	"LAND" VARCHAR2(255 BYTE),
	"TELEFON" VARCHAR2(255 BYTE),
	"MOBILE" VARCHAR2(255 BYTE),
	"MAIL" VARCHAR2(1024 BYTE),
	"KONTAKTTYP" VARCHAR2(5 BYTE),
	"KONTAKDATUM" DATE,
	"QUARANTAENE_START" DATE,
	"QUARANTAENE_ENDE" DATE,
	"ARBEITSINFOS" CLOB,
	"KOMMENTARE" CLOB,
	"HAUSHALT" VARCHAR2(1024 BYTE),
	"TELEFONNOTIZEN" CLOB,
	"DOKU" CLOB
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "COVE"
 LOB ("ARBEITSINFOS") STORE AS SECUREFILE (
  TABLESPACE "COVE" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES )
 LOB ("KOMMENTARE") STORE AS SECUREFILE (
  TABLESPACE "COVE" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES )
 LOB ("TELEFONNOTIZEN") STORE AS SECUREFILE (
  TABLESPACE "COVE" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES )
 LOB ("DOKU") STORE AS SECUREFILE (
  TABLESPACE "COVE" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Index PERSON_NAME_INDEX
--------------------------------------------------------

  CREATE INDEX "COVE"."PERSON_NAME_INDEX" ON "COVE"."PERSON" ("NAME")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "COVE" ;
--------------------------------------------------------
--  DDL for Index PERSON_VORNAME_INDEX
--------------------------------------------------------

  CREATE INDEX "COVE"."PERSON_VORNAME_INDEX" ON "COVE"."PERSON" ("VORNAME")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "COVE" ;
--------------------------------------------------------
--  DDL for Index PERSON_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "COVE"."PERSON_PK" ON "COVE"."PERSON" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "COVE" ;
--------------------------------------------------------
--  Constraints for Table PERSON
--------------------------------------------------------

  ALTER TABLE "COVE"."PERSON" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "COVE"."PERSON" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "COVE"."PERSON" MODIFY ("VORNAME" NOT NULL ENABLE);
  ALTER TABLE "COVE"."PERSON" ADD CONSTRAINT "PERSON_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "COVE"  ENABLE;


--------------------------------------------------------
--  DDL for Table PROBE
--------------------------------------------------------

  CREATE TABLE "COVE"."PROBE"
   (
   	"CREATED_DATE" DATE,
	"KOMMENTAR" VARCHAR2(1024 BYTE),
	"DATUM" DATE,
	"ERGEBNIS" VARCHAR2(255 BYTE),
	"PERSONID" VARCHAR2(1024 BYTE)
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "COVE" ;
--------------------------------------------------------
--  DDL for Index PROBE_FK
--------------------------------------------------------

  CREATE INDEX "COVE"."PROBE_FK" ON "COVE"."PROBE" ("PERSONID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "COVE" ;
--------------------------------------------------------
--  DDL for Index PROBE_DATUM_INDEX
--------------------------------------------------------

  CREATE INDEX "COVE"."PROBE_DATUM_INDEX" ON "COVE"."PROBE" ("DATUM")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "COVE" ;
--------------------------------------------------------
--  Constraints for Table PROBE
--------------------------------------------------------

  ALTER TABLE "COVE"."PROBE" MODIFY ("PERSONID" NOT NULL ENABLE);
  ALTER TABLE "COVE"."PROBE" MODIFY ("ERGEBNIS" NOT NULL ENABLE);


--------------------------------------------------------
--  DDL for Table KONTAKT
--------------------------------------------------------

  CREATE TABLE "COVE"."KONTAKT"
   (	"ID" VARCHAR2(1024 BYTE),
	"CREATED_DATE" DATE,
	"PERSONID" VARCHAR2(1024 BYTE),
	"KONTAKTMIT" VARCHAR2(1024 BYTE),
	"KOMMENTAR" VARCHAR2(1024 BYTE),
	"KONTAKTTYP" VARCHAR2(5 BYTE),
	"KONTAKTDATUM" DATE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COVE" ;
--------------------------------------------------------
--  DDL for Index KONTAKT_DATUM_INDEX
--------------------------------------------------------

  CREATE INDEX "COVE"."KONTAKT_DATUM_INDEX" ON "COVE"."KONTAKT" ("KONTAKTDATUM")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COVE" ;
--------------------------------------------------------
--  DDL for Index KONTAKT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "COVE"."KONTAKT_PK" ON "COVE"."KONTAKT" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COVE" ;
--------------------------------------------------------
--  DDL for Index KONTAKT_PERSON2_INDEX
--------------------------------------------------------

  CREATE INDEX "COVE"."KONTAKT_PERSON2_INDEX" ON "COVE"."KONTAKT" ("KONTAKTMIT")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COVE" ;
--------------------------------------------------------
--  DDL for Index KONTAKT_PERSON1_INDEX
--------------------------------------------------------

  CREATE INDEX "COVE"."KONTAKT_PERSON1_INDEX" ON "COVE"."KONTAKT" ("PERSONID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COVE" ;
--------------------------------------------------------
--  DDL for Index KONTAKT_KONTAKTTYP_INDEX
--------------------------------------------------------

  CREATE INDEX "COVE"."KONTAKT_KONTAKTTYP_INDEX" ON "COVE"."KONTAKT" ("KONTAKTTYP")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COVE" ;
--------------------------------------------------------
--  Constraints for Table KONTAKT
--------------------------------------------------------

  ALTER TABLE "COVE"."KONTAKT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "COVE"."KONTAKT" ADD CONSTRAINT "KONTAKT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COVE"  ENABLE;
  ALTER TABLE "COVE"."KONTAKT" ADD CONSTRAINT "KONTAKT_CHK1" CHECK (PERSONID <> KONTAKTMIT) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table KONTAKT
--------------------------------------------------------

  ALTER TABLE "COVE"."KONTAKT" ADD CONSTRAINT "KONTAKT_FK_PERSON" FOREIGN KEY ("PERSONID")
	  REFERENCES "COVE"."PERSON" ("ID") ENABLE;
  ALTER TABLE "COVE"."KONTAKT" ADD CONSTRAINT "KONTAKT_FK_KONTAKTMIT" FOREIGN KEY ("KONTAKTMIT")
	  REFERENCES "COVE"."PERSON" ("ID") ENABLE;


