ALTER TABLE "COVE"."PERSON" MODIFY "KPBIS" TIMESTAMP;
ALTER TABLE "COVE"."PERSON" MODIFY "LETZTERKONTAKT" TIMESTAMP;
ALTER TABLE "COVE"."PERSON" MODIFY "ERSTKONTAKT" TIMESTAMP;
ALTER TABLE "COVE"."PERSON" MODIFY "ENDTELEFONAT" TIMESTAMP;